# Generated by Django 3.0.3 on 2020-02-28 21:54

from django.db import migrations, models
import django.db.models.deletion
import rest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('address', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('blood_group', models.CharField(choices=[(rest.models.BloodGroup['A_P'], 'A+'), (rest.models.BloodGroup['A_N'], 'A-'), (rest.models.BloodGroup['B_P'], 'B+'), (rest.models.BloodGroup['B_N'], 'B-'), (rest.models.BloodGroup['AB_P'], 'AB+'), (rest.models.BloodGroup['AB_N'], 'AB-'), (rest.models.BloodGroup['O_P'], 'O+'), (rest.models.BloodGroup['O_N'], 'O-')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admitted_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='O_P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.BloodBank')),
            ],
        ),
        migrations.CreateModel(
            name='O_N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.BloodBank')),
            ],
        ),
        migrations.CreateModel(
            name='B_P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.BloodBank')),
            ],
        ),
        migrations.CreateModel(
            name='B_N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.BloodBank')),
            ],
        ),
        migrations.CreateModel(
            name='AB_P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.BloodBank')),
            ],
        ),
        migrations.CreateModel(
            name='AB_N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.BloodBank')),
            ],
        ),
        migrations.CreateModel(
            name='A_P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.BloodBank')),
            ],
        ),
        migrations.CreateModel(
            name='A_N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.BloodBank')),
            ],
        ),
    ]
